### ISSUE TITLE
SpaceTimeRealigner dev version

### ISSUE THREAD

**Issue by damaggu** [IBT-FMI/SAMRI#1]
Hey Christian,

when running the pipeline, the realigner throws this exception. Somehow the version of the nipy.SpaceTimeRealigner doesn't match the required one. How do I get rid of this?

Very best

> Traceback: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nipype-0.12.1-py2.7.egg/nipype/pipeline/plugins/multiproc.py", line 49, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/lib/python2.7/site-packages/nipype-0.12.1-py2.7.egg/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/usr/local/lib/python2.7/site-packages/nipype-0.12.1-py2.7.egg/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/lib/python2.7/site-packages/nipype-0.12.1-py2.7.egg/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/usr/local/lib/python2.7/site-packages/nipype-0.12.1-py2.7.egg/nipype/interfaces/base.py", line 1029, in run
    self._check_version_requirements(self.inputs)
  File "/usr/local/lib/python2.7/site-packages/nipype-0.12.1-py2.7.egg/nipype/interfaces/base.py", line 966, in _check_version_requirements
    version, min_ver))
Exception: Trait in_file (SpaceTimeRealigner) (version 0.4.0 < required 0.4.0.dev)

**Comment by TheChymera** [comment]
Ok, so I looked this up, and I think the strange question here is why **I** do not get the same error, though I use the same versions. In any case, your [error has been reported before](https://github.com/nipy/nipype/issues/1066), and can apparently be fixed by installing the newest nipy (live) directly from GitHub:

**Comment by TheChymera** [comment]
@damaggu has the newer nipy worked for you? If so, we should close this issue.

**Comment by damaggu** [comment]
Yes no issues with the newer version, thanks
